import { CheckCircle2, CreditCard, LockKeyhole } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useI18n } from '../../i18n/I18nContext';
import { socialService } from '../../services/social.service';
import { Button } from '../common/Button';

export function DonationPanel({ programSlug }: { programSlug?: string }) {
  const { formatNumber, localize } = useI18n();
  const [amount, setAmount] = useState(10000); const [intentId, setIntentId] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (amount < 1000) { setError(localize('Նվազագույն գումարը 1,000 ֏ է։')); return; } setLoading(true); try { const intent = await socialService.createDonationIntent({ amount, currency: 'AMD', programSlug }); setIntentId(intent.providerReference); } catch { setError(localize('Չհաջողվեց ստեղծել նվիրատվության intent-ը։')); } finally { setLoading(false); } }
  if (intentId) return <div className="bg-parchment p-7 text-center"><CheckCircle2 className="mx-auto size-9 text-forest" /><h3 className="mt-4 font-display text-2xl font-bold text-episcopal">{localize('Mock intent-ը ստեղծված է')}</h3><p className="mt-3 text-sm text-ink/55">{localize('Վճարում չի կատարվել։ Հղում՝')} {intentId.slice(0, 14)}</p><Button className="mt-6" onClick={() => setIntentId('')}>{localize('Նոր intent')}</Button></div>;
  return <form className="bg-episcopal p-6 text-parchment sm:p-8" onSubmit={submit}><CreditCard className="size-7 text-gold" /><h3 className="mt-5 font-display text-3xl font-bold">{localize('Աջակցել հիմա')}</h3><p className="mt-3 text-sm leading-7 text-parchment/60">{localize('MVP mock հոսք է. քարտային կամ վճարային տվյալներ չեն պահանջվում և չեն պահպանվում։')}</p><div className="mt-6 grid grid-cols-3 gap-2">{[5000,10000,25000].map((v) => <button className={`rounded-full border px-2 py-2 text-xs font-bold ${amount === v ? 'border-gold bg-gold text-episcopal' : 'border-parchment/20'}`} key={v} onClick={() => setAmount(v)} type="button">{formatNumber(v)} ֏</button>)}</div><label className="mt-5 block text-xs font-bold uppercase tracking-[.14em] text-gold">{localize('Այլ գումար')}<input className="focus-ring mt-2 min-h-12 w-full border border-parchment/20 bg-parchment/10 px-4 text-parchment" min={1000} type="number" value={amount} onChange={(e) => setAmount(Number(e.target.value))} /></label>{error && <p className="mt-3 text-xs text-gold">{error}</p>}<Button className="mt-6 w-full" disabled={loading} type="submit" variant="light">{loading ? localize('Ստեղծվում է...') : localize('Ստեղծել mock donation intent')}</Button><p className="mt-4 flex gap-2 text-[10px] leading-5 text-parchment/40"><LockKeyhole className="mt-0.5 size-3 shrink-0" />{localize('Provider-ready architecture՝ Arca, Visa, PayPal, Apple Pay և Google Pay ինտեգրումների համար։')}</p></form>;
}
